import { uid } from "./utils.js";
export const columns = [
  { id: "todo", name: "To Do" },
  { id: "progress", name: "In Progress", limit: 5 },
  { id: "review", name: "Review", limit: 3 },
  { id: "done", name: "Done" },
];
export const seed = [
  {
    id: uid("task"),
    title: "Shape the jasmine identity",
    description: "Refine the visual language, logo rhythm and type pairing.",
    priority: "high",
    label: "design",
    assignee: "kahtan",
    deadline: "2026-09-25",
    estimatedHours: 4,
    columnId: "todo",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Sketch three directions", done: true },
      { id: uid("sub"), text: "Select final mark", done: false },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Draft the color system",
    description: "Define semantic tokens, contrast pairs and dark mode ramp.",
    priority: "high",
    label: "design",
    assignee: "Ari",
    deadline: "2026-09-27",
    estimatedHours: 5,
    columnId: "todo",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Audit current palette", done: false },
      { id: uid("sub"), text: "Name semantic tokens", done: false },
      { id: uid("sub"), text: "Check contrast ratios", done: false },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Set up project scaffolding",
    description: "Bundler, linting, formatting and the base folder structure.",
    priority: "medium",
    label: "development",
    assignee: "Noah",
    deadline: "2026-09-26",
    estimatedHours: 3,
    columnId: "todo",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Init package", done: false },
      { id: uid("sub"), text: "Add lint config", done: false },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Plan user research interviews",
    description: "Recruit five participants and write the discussion guide.",
    priority: "medium",
    label: "research",
    assignee: "Mira",
    deadline: "2026-09-30",
    estimatedHours: 4,
    columnId: "todo",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Shortlist participants", done: false },
      { id: uid("sub"), text: "Draft discussion guide", done: false },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Prepare analytics events",
    description: "Map the key board actions to a small, stable event schema.",
    priority: "low",
    label: "development",
    assignee: "Noah",
    deadline: "2026-10-02",
    estimatedHours: 3,
    columnId: "todo",
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [],
    comments: [],
  },

  {
    id: uid("task"),
    title: "Build task interactions",
    description: "Connect editing, filters and smooth board movement.",
    priority: "medium",
    label: "development",
    assignee: "Noah",
    deadline: "2026-09-24",
    estimatedHours: 6,
    columnId: "progress",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: new Date(Date.now() - 86400000).toISOString(),
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Task modal", done: true },
      { id: uid("sub"), text: "Drag and drop", done: true },
      { id: uid("sub"), text: "Persistence", done: false },
    ],
    comments: [
      {
        id: uid("com"),
        author: "kahtan",
        text: "Keep the transitions quiet and tactile.",
        timestamp: new Date(Date.now() - 7200000).toISOString(),
        edited: false,
      },
    ],
  },
  {
    id: uid("task"),
    title: "Wire up task persistence",
    description: "Sync board state to storage and restore it on reload.",
    priority: "high",
    label: "development",
    assignee: "Noah",
    deadline: "2026-09-23",
    estimatedHours: 5,
    columnId: "progress",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: new Date(Date.now() - 43200000).toISOString(),
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Serialize board state", done: true },
      { id: uid("sub"), text: "Handle schema drift", done: false },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Design empty states",
    description: "Illustrations and copy for boards with no tasks yet.",
    priority: "low",
    label: "design",
    assignee: "Ari",
    deadline: "2026-09-28",
    estimatedHours: 3,
    columnId: "progress",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: new Date(Date.now() - 21600000).toISOString(),
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Empty column", done: true },
      { id: uid("sub"), text: "Empty board", done: false },
      { id: uid("sub"), text: "No results", done: false },
    ],
    comments: [],
  },

  {
    id: uid("task"),
    title: "Write launch notes",
    description: "Prepare a concise handoff for the next review.",
    priority: "low",
    label: "documentation",
    assignee: "Ari",
    deadline: "2026-09-29",
    estimatedHours: 2,
    columnId: "review",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Outline", done: true },
      { id: uid("sub"), text: "Screenshots", done: true },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Review onboarding copy",
    description: "Tighten the first-run messaging and empty state text.",
    priority: "medium",
    label: "documentation",
    assignee: "Mira",
    deadline: "2026-09-26",
    estimatedHours: 2,
    columnId: "review",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "First run", done: true },
      { id: uid("sub"), text: "Tooltips", done: true },
    ],
    comments: [
      {
        id: uid("com"),
        author: "Ari",
        text: "Second pass reads much cleaner.",
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        edited: false,
      },
    ],
  },

  {
    id: uid("task"),
    title: "Accessibility pass",
    description: "Keyboard paths, focus states and reduced motion.",
    priority: "medium",
    label: "testing",
    assignee: "kahtan",
    deadline: "2026-09-22",
    estimatedHours: 3,
    columnId: "done",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    completedAt: new Date(Date.now() - 86400000).toISOString(),
    subtasks: [
      { id: uid("sub"), text: "Focus states", done: true },
      { id: uid("sub"), text: "Keyboard shortcuts", done: true },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Set up CI pipeline",
    description: "Lint, test and preview builds on every pull request.",
    priority: "medium",
    label: "development",
    assignee: "Noah",
    deadline: "2026-09-21",
    estimatedHours: 4,
    columnId: "done",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    completedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    subtasks: [
      { id: uid("sub"), text: "Lint job", done: true },
      { id: uid("sub"), text: "Preview deploy", done: true },
    ],
    comments: [],
  },
];
export const blankTask = (columnId) => ({
  id: uid("task"),
  title: "",
  description: "",
  priority: "medium",
  label: "",
  assignee: "",
  deadline: "",
  estimatedHours: "",
  columnId,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  startedAt: null,
  completedAt: null,
  subtasks: [],
  comments: [],
});