import { uid } from "./utils.js";
export const columns = [
  { id: "todo", name: "To Do" },
  { id: "progress", name: "In Progress", limit: 5 },
  { id: "review", name: "Review", limit: 3 },
  { id: "done", name: "Done" },
];
export const seed = [
  {
    id: uid("task"),
    title: "Shape the jasmine identity",
    description: "Refine the visual language, logo rhythm and type pairing.",
    priority: "high",
    label: "design",
    assignee: "kahtan",
    deadline: "2026-09-25",
    estimatedHours: 4,
    columnId: "todo",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Sketch three directions", done: true },
      { id: uid("sub"), text: "Select final mark", done: false },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Build task interactions",
    description: "Connect editing, filters and smooth board movement.",
    priority: "medium",
    label: "development",
    assignee: "Noah",
    deadline: "2026-09-24",
    estimatedHours: 6,
    columnId: "progress",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: new Date(Date.now() - 86400000).toISOString(),
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Task modal", done: true },
      { id: uid("sub"), text: "Drag and drop", done: true },
      { id: uid("sub"), text: "Persistence", done: false },
    ],
    comments: [
      {
        id: uid("com"),
        author: "kahtan",
        text: "Keep the transitions quiet and tactile.",
        timestamp: new Date(Date.now() - 7200000).toISOString(),
        edited: false,
      },
    ],
  },
  {
    id: uid("task"),
    title: "Write launch notes",
    description: "Prepare a concise handoff for the next review.",
    priority: "low",
    label: "documentation",
    assignee: "Ari",
    deadline: "2026-09-29",
    estimatedHours: 2,
    columnId: "review",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: null,
    completedAt: null,
    subtasks: [
      { id: uid("sub"), text: "Outline", done: true },
      { id: uid("sub"), text: "Screenshots", done: true },
    ],
    comments: [],
  },
  {
    id: uid("task"),
    title: "Accessibility pass",
    description: "Keyboard paths, focus states and reduced motion.",
    priority: "medium",
    label: "testing",
    assignee: "kahtan",
    deadline: "2026-09-22",
    estimatedHours: 3,
    columnId: "done",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
    startedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    completedAt: new Date(Date.now() - 86400000).toISOString(),
    subtasks: [
      { id: uid("sub"), text: "Focus states", done: true },
      { id: uid("sub"), text: "Keyboard shortcuts", done: true },
    ],
    comments: [],
  },
];
export const blankTask = (columnId) => ({
  id: uid("task"),
  title: "",
  description: "",
  priority: "medium",
  label: "",
  assignee: "",
  deadline: "",
  estimatedHours: "",
  columnId,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  startedAt: null,
  completedAt: null,
  subtasks: [],
  comments: [],
});
